language: bash
os: windows
env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
install:
  - choco install nuget.commandline
  - nuget restore LSSCLI.sln
script:
  - export PATH="$MSBUILD_PATH:$PATH"
  - MSBuild.exe //p:Configuration=Release LSSCLI.sln
  - "if [ $TRAVIS_TAG ]; then zip -j LSS\\ CLI.$TRAVIS_TAG.zip LSS\\ CLI/bin/Release/lssc.exe* LSS\\ CLI/bin/Release/*.dll; fi"
deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_KEY
  file: LSS CLI.$TRAVIS_TAG.zip
    on:
      tags: true
