language: bash
os: windows
env:
  - MSBUILD_PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
install:
  - choco install nuget.commandline
  - nuget restore LSSCLI.sln
script:
  - export PATH="$MSBUILD_PATH:$PATH"
  - MSBuild.exe //p:Configuration=Release LSSCLI.sln
# Build only in the master branch
branches:
  only:
  - master
